---

- name: "Go-Lang | Get $HOME"
  command: "echo $HOME"
  register: shell_home_dir
  changed_when: false

- name: "Go-Lang | Define GOROOT"
  set_fact:
    GOROOT: /usr/bin/go
  # when: GOROOT is not defined

- name: "Go-Lang | Define GOPATH"
  set_fact:
    GOPATH: "{{ shell_home_dir.stdout }}/go"

- name: "Go-Lang | Define GOPROXY"
  set_fact:
    GOPROXY: ""

- name: "Go-Lang | Define shell exports"
  set_fact:
    shell_exports:
      - regex: "export GOROOT"
        lineinfile: "export GOROOT={{ GOROOT }}"
      - regex: "export GOPATH"
        lineinfile: "export GOPATH={{ GOPATH }}"
      - regex: "export GOPROXY={{ GOPROXY }}"
        lineinfile: "export GOPROXY={{ GOPROXY }}"
      - regex: "PATH:{{ GOROOT }}/bin"
        lineinfile: "export PATH=$PATH:{{ GOROOT }}/bin"
      - regex: "PATH:{{ GOPATH }}/bin"
        lineinfile: "export PATH=$PATH:{{ GOPATH }}/bin"
