# ansible-galaxy install mikolak-net.raspi_config
---

- hosts:
    - all
  become: true
  roles:
    - mikolak-net.raspi_config
  vars:
    # perform full update+upgrade
    # raspi_config_update_packages: yes

    # have the FS fill the SD card
    # raspi_config_expanded_filesystem: yes

    # how much memory should be owned by the GPU (vs RAM)
    # raspi_config_memory_split_gpu: 16

    #currently sets Pi2 OC setting if applicable
    # raspi_config_ensure_optimal_cpu_params: yes

    # set global locale
    raspi_config_locale: en_US.UTF-8

    # set timezone
    # raspi_config_timezone: UTC
    raspi_config_timezone: Europe/Athens

    # list of services that should be restarted if the timezone is changed
    # raspi_config_timezone_dependent_services: []

    # set hostname
    raspi_config_hostname: pi-one

    # ensure camera support is on - CURRENTLY UNVERIFIED
    raspi_config_enable_camera: yes

    # specify whether to fail deployment when user/password is default
    # ignored if "raspi_config_replace_user" is set (warning will still display)
    raspi_config_fail_on_auth_test: yes

    # user to replace the default "pi" user with
    # NOTE: if you use this for the first time as "pi", any post_tasks will fail!
    raspi_config_replace_user:
      name: pi
      #LOCAL path to your public key file
      path_to_ssh_key: /Users/giorgospapaefthimiou/.ssh/id_rsa.pub

    # wait this many seconds before forcing connection retry after reboot
    raspi_config_reboot_max_wait_time: 60

    # use this to add any additional options to the config in raw form
    # raspi_config_other_options: {}
