kernel_params:
  - { param: 'net.core.somaxconn', value: '4096' }
  - { param: 'net.ipv4.tcp_max_syn_backlog', value: '4096' }
  - { param: 'net.ipv4.tcp_tw_reuse', value: '1' }
  # Reference: https://ma.ttias.be/linux-increase-ip_local_port_range-tcp-port-range/
  - { param: 'net.ipv4.ip_local_port_range', value: '"10240 65535"' }

kernel_params_for_lt_4_12:
  # Reference: https://gitlab.com/Centech/centaur-tech/wikis/post-mortems/%5Bpost-mortem%5D-Production-server-reachability-problem
  - { param: 'net.ipv4.tcp_tw_recycle', value: '0' }
