---

- name: Update all packages to the latest version
  apt:
    upgrade: dist
    update_cache: yes
    force_apt_get: yes

- name: Required packages installed
  apt:
    state: latest
    pkg: [
      'git',
      'vim',
      'wget',
      'curl',
      'jq',
      'multitail',
      'htop',
      'supervisor',
      'ntp',
      'python',
      'python3',
      'python-rpi.gpio',
      'python3-rpi.gpio'
    ]
    force_apt_get: yes
  tags:
    - install

- name: Remove useless packages from the cache
  apt:
    autoclean: yes
    force_apt_get: yes
