---

- name: Required packages installed
  apt:
    state: latest
    pkg: [
      'build-essential',
      'openssl',
      'libssl-dev',
      'autoconf',
      'gcc',
      'libc6',
      'libmcrypt-dev',
      'make',
      'bc',
      'gawk',
      'dc',
      'gettext',
      'wget',
      'curl',
      'jq',
      'multitail',
      'htop'
    ]
    update_cache: yes
  tags:
    - install