---

- name: Disable Password Authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: PasswordAuthentication no
    state: present
    backup: yes
  register: sshd_config

- name: Check sshd_config validity
  shell: sshd -t
  when: sshd_config is changed
  notify:
    - restart ssh

- name: Allow 'sudo' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Create '{{ default_user }}' user and assign appropriate groups
  user:
    name: "{{ default_user }}"
    shell: /bin/bash
    createhome: yes
    password: "{{ default_user_password }}"
    groups: adm,dialout,cdrom,floppy,sudo,audio,dip,video,plugdev,netdev
    append: yes
  when: ansible_user != default_user

- name: Set authorized key took from file
  authorized_key:
    user: "{{ default_user }}"
    state: present
    key: "{{ ansible_ssh_public_key }}"
