---

- name: update /etc/motion/motion.conf
  template:
    src: motion.conf.j2
    dest: "/etc/motion/motion.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  become: true
  tags:
    - config
